COLUMNS = [
	'URN',
	'LA (code)',
	'LA (name)',
	'EstablishmentNumber',
    'EstablishmentName',
	'TypeOfEstablishment (name)',
    'EstablishmentStatus (name)',
	'ReasonEstablishmentOpened (name)',
    'OpenDate',
	'PhaseOfEducation (name)',
	'StatutoryLowAge',
    'StatutoryHighAge',
	'Gender (name)',
	'Street',
	'Locality',
	'Address3',
    'Town',
	'County (name)',
	'Postcode',
	'SchoolWebsite',
	'MainEmail',
    'TelephoneNum',
	'HeadTitle (name)',
	'HeadFirstName',
	'HeadLastName',
    'HeadPreferredJobTitle',
	'Region',
	'FOI sent?',
	'FOI acknowledged?',
    'FOI received on:',
	'Expected response date',
	'Response received?',
    'Response received on:',
	'Response refused?',
	'Special school?',
    'Any GCSE students?',
	'Any A level students?',
    '1a). Homework: any departments?',
	'1b). Homework: all departments?',
    '2a). Mock exams: any departments?',
    '2b). Mock exams: all departments?',
    '3a). In-school assessments: any departments?',
    '3b). In-school assessments: all departments?',
    '4a). JCQ M1 forms since 01/04/2021',
    '4b). JCQ M1 forms so far in 2020-21',
	'4c). JCQ M1 forms in 2019-2020',
    '4d). JCQ M1 forms in 2018-19',
	'5a). JCQ M2 forms since 01/04/2021',
    '5b). JCQ M2 forms so far in 2020-21',
	'5c). JCQ M2 forms in 2019-20',
    '5d). JCQ M2 forms in 2018-19',
    '6a). Any mock exams/assessments invigilated by external invigilators?',
    '6b). Any pupils aware of exam content prior to taking them?',
	'6c). Any students taking exams written by normal class teacher?',
	'6d). Number of GCSE students with access arrangements',
	'6e). Number of A level students with access arrangements',
	'7ai). GCSE appeals: 2017-18',
	'7aii). GCSE appeals: 2018-19',
	'7aiii). GCSE appeals: 2019-20',
	'7bi). A level appeals: 2017-18',
	'7bii). A level appeals: 2018-19',
	'7biii). A level appeals: 2019-20',
	'8a). 2019-20 letters threatening judicial review over GCSE grades',
	'8b). 2019-20 letters threatening judicial review over A level grades',
	'Context/notes'
]